# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand


p <- plot_metrics(df = metrics_df, weekly = TRUE, app_name = "FIND Sars-CoV-2 Test tracker")

test_that("plot_metrics works", {
  expect_s3_class(object = p, class = "ggplot")
  
})

