# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

app <- c("FINDCov19Tracker")
app_name <- c("FIND Sars-CoV-2 Test tracker")
server <- rep("shinyapps.io", length(app))
from <- rep("2023-09-01 0:00:00", length(app))
until <- rep("2023-12-12 0:00:00", length(app))

metrics_df <- metrics(app = app, app_name = app_name, 
                                    server = server, from = from, until = until)

test_that("metrics works", {
  expect_s3_class(object = metrics_df, class = "data.frame")
  expect_length(object = metrics_df, n = 3)
  expect_that(nrow(metrics_df), equals(103))
})
