# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' metrics Produce metrics for shiny app
#'
#' @return A data frame with number of connections per day for the given shiny application
#' @param app The name of the app on the shinyapps.io server
#' @param app_name The name of the the application, to be used for plots and titles
#' @param server The server where the shiny app is hosted
#' @param from The date and time from when the metrics should be measured from
#' @param until The date and time until when the metrics should be measured from
#' @importfrom magrittr set_colnames
#' @importfrom rsconnect showMetrics
#' @importfrom dplyr mutate select arrange group_by summarise case_when
#' @importfrom tidyr gather
#' @importfrom lubridate date as_datetime
#' @export 
#'
#' @examples
#' app <- c("FINDCov19Tracker")
#' app_name <- c("FIND Sars-CoV-2 Test tracker")
#' server <- rep("shinyapps.io", length(app))
#' from <- rep("2023-09-01 0:00:00", length(app))
#' until <- rep("2023-12-12 0:00:00", length(app))
#' 
#' metrics_df <- metrics(app = app, app_name = app_name, 
#'                                     server = server, from = from, until = until)
#' 
metrics <- function(app = "FINDCov19Policy", app_name = "FIND Sars-CoV-2 Policy dashboard", 
                    server="shinyapps.io", from = "2022-09-01 0:00:00", until = "2022-12-12 0:00:00"){
  df <- rsconnect::showMetrics("container_status",
                               c("connect_count", 
                                 "connect_procs"),
                               appName = app,
                               server = server,
                               from = as.numeric(as.POSIXct(from)),
                               until = as.numeric(as.POSIXct(until)),
                               interval="1m"
  ) %>%
    magrittr::set_colnames(c("dummy", "timestamp", "connect_count", "connect_procs")) %>%
    dplyr::mutate(across(c("timestamp", "connect_count", "connect_procs"), as.numeric)) %>%
    dplyr::mutate(date=lubridate::as_datetime(timestamp)) %>% 
    dplyr::select(-timestamp) %>% 
    dplyr::arrange(date) %>% 
    dplyr::mutate(date = lubridate::date(date),
           new_connect=dplyr::case_when(
             connect_count>lag(connect_count,1) ~ connect_count-lag(connect_count,1),
             TRUE ~ 0)) %>%
    dplyr::group_by(date) %>%
    dplyr::summarise(
      n_count=sum(connect_count),
      n_procs=sum(connect_procs),
      n_connect=sum(new_connect) # approximate) %>%
    ) %>%  
    dplyr::select(n_connect, date) %>% 
    tidyr::gather(key="key", value="value", -date) %>%
    dplyr::mutate(key = app_name)
  
  return(df)
}


