# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' plot_metrics Produce metrics for shiny app
#'
#' @return A plot with number of connections per day for the given shiny application
#' @param df A data frame with number of connections per day for the given shiny application, produced by metrics function
#' @param weekly Logical variable, TRUE if plot should be showcasing number of connections by week, FALSE for number of connections per day
#' @param app_name The name of the the application, to be used for plots and titles
#' @import ggplot2
#' @importfrom shinyfind pal_find
#' @importfrom dplyr  group_by summarise 
#' @importfrom tidyr gather
#' @importfrom lubridate as_date
#' @export 
#'
#' @examples
#' p <- plot_metrics(df = metrics_df, weekly = TRUE, app_name = "FIND Sars-CoV-2 Test tracker")
#' print(p)
#' 
plot_metrics <- function(df = metrics_df, weekly = TRUE, app_name = "FIND Sars-CoV-2 Test tracker"){
  df <- subset(df, key == app_name)
  
  if(isTRUE(weekly)){
    df <- df %>%
      dplyr::group_by(date = cut(date, "week"), key) %>% 
      dplyr::summarise(value = sum(value))
    df$date <- lubridate::as_date(df$date)
    
    p <- ggplot(df) +
      labs(title="Number of connections for FIND shiny applications (weekly)", x="", y="") +
      geom_line(aes(x=date, y=value, colour=key)) +
      facet_wrap(~key) + 
      scale_color_manual(values = shinyfind::pal_find()) +
      theme_light()
    
  } else {
    df <- df
    p <- ggplot(df) +
      labs(title="Number of connections for FIND shiny applications (daily)", x="", y="") +
      geom_line(aes(x=date, y=value, colour=key)) +
      facet_wrap(~key) + 
      scale_color_manual(values = shinyfind::pal_find()) +
      theme_light()
  }
  
 return(p)
}

